name: lc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.7
  - libopencv=4.2.0
  - opencv=4.2.0
  - py-opencv=4.2.0
  - ffmpeg=4.2
  - pillow=7.0.0
  - pip=20.0.2
  - scikit-image=0.16.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - sympy=1.5.1
  - tqdm=4.44.1
  - imageio=2.8.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jupyter=1.0.0
  - jupyter_client=6.1.2
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.1.0
  - notebook=6.0.3
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - requests=2.23.0
  - pip:
    - autograd==1.3
